name: traffic_crashes
version: '1.0.0'
config-version: 2

profile: traffic_crashes

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  traffic_crashes:
    staging:
      +materialized: view
